import {cleanup,fireEvent,render,screen,waitFor} from "@testing-library/react";import {afterEach,beforeEach,expect,it,vi} from "vitest";import {App} from "./App";
const project={path:"C:/workspace",name:"workspace",active:true};
const session={session_id:"session-1",workdir:project.path,provider:"test",model:"model",is_open:false,title:"First task",message_count:0};
beforeEach(()=>{window.noval={chooseWorkspace:vi.fn().mockResolvedValue(null),getWorkspace:vi.fn().mockResolvedValue(null),listProjects:vi.fn().mockResolvedValue([]),projectSessions:vi.fn().mockResolvedValue([]),activateProject:vi.fn().mockResolvedValue(project.path),removeProject:vi.fn().mockResolvedValue([]),revealProject:vi.fn(),listSessions:vi.fn().mockResolvedValue([]),createSession:vi.fn(),resumeSession:vi.fn(),renameSession:vi.fn(),transcript:vi.fn().mockResolvedValue({entries:[],next_sequence:0,has_more:false}),replayEvents:vi.fn().mockResolvedValue({events:[],next_sequence:0,gap_detected:false,has_more:false}),startTurn:vi.fn(),cancelTurn:vi.fn(),setPermissionMode:vi.fn(),revokeTool:vi.fn(),resetPermissions:vi.fn(),resolvePermission:vi.fn(),onEvent:vi.fn().mockReturnValue(()=>{}),appInfo:vi.fn(),getProviderProfile:vi.fn().mockResolvedValue(null),saveProviderProfile:vi.fn()} as any});
afterEach(cleanup);
it("keeps the single-page shell visible before a project is added",async()=>{render(<App/>);expect(await screen.findByRole("button",{name:/add project/i})).toBeVisible();expect(screen.getByText(/Your work starts with a project/i)).toBeVisible();expect(screen.queryByText(/Choose workspace/i)).not.toBeInTheDocument()});
it("shows Sessions below their project and renames the active Session",async()=>{vi.mocked(window.noval.listProjects).mockResolvedValue([project]);vi.mocked(window.noval.projectSessions).mockResolvedValue([session]);vi.mocked(window.noval.resumeSession).mockResolvedValue({session:{...session,is_open:true},permissions:{mode:"ask",approved_tools:[]}});vi.mocked(window.noval.renameSession).mockResolvedValue({...session,is_open:true,title:"Renamed task"});render(<App/>);fireEvent.click(await screen.findByRole("button",{name:/first task/i}));fireEvent.click(await screen.findByRole("button",{name:/rename task/i}));fireEvent.change(screen.getByRole("textbox",{name:/task title/i}),{target:{value:"Renamed task"}});fireEvent.click(screen.getByRole("button",{name:/save title/i}));await waitFor(()=>expect(window.noval.renameSession).toHaveBeenCalledWith("session-1","Renamed task"));expect((await screen.findAllByText("Renamed task")).length).toBeGreaterThan(0)});
it("shows Core completion evidence separately from the answer",async()=>{vi.mocked(window.noval.listProjects).mockResolvedValue([project]);vi.mocked(window.noval.projectSessions).mockResolvedValue([session]);vi.mocked(window.noval.resumeSession).mockResolvedValue({session:{...session,is_open:true},permissions:{mode:"ask",approved_tools:[]}});vi.mocked(window.noval.startTurn).mockResolvedValue({status:"completed",completion:{goal_id:"g1",status:"uncertain",evaluated_at:"2026-07-22T00:00:00Z",criteria:[{criterion_id:"tests",status:"missing",source:null,observed_at:null}]}});render(<App/>);fireEvent.click(await screen.findByRole("button",{name:/first task/i}));fireEvent.change(await screen.findByRole("textbox",{name:/message noval/i}),{target:{value:"Do the work"}});fireEvent.click(screen.getByRole("button",{name:/send/i}));expect(await screen.findByRole("region",{name:/completion evidence/i})).toHaveTextContent("Completion uncertain")});
it("shows five Sessions per project until the user expands the tree",async()=>{vi.mocked(window.noval.listProjects).mockResolvedValue([project]);vi.mocked(window.noval.projectSessions).mockResolvedValue(Array.from({length:7},(_,index)=>({...session,session_id:`session-${index}`,title:`Task ${index+1}`})));render(<App/>);expect(await screen.findByRole("button",{name:"Task 5"})).toBeVisible();expect(screen.queryByRole("button",{name:"Task 6"})).not.toBeInTheDocument();fireEvent.click(screen.getByRole("button",{name:/Show 2 more/i}));expect(screen.getByRole("button",{name:"Task 6"})).toBeVisible()});
