import {FormEvent,useEffect,useMemo,useRef,useState} from "react";
import {ArrowUp,AtSign,Check,CheckCircle2,Copy,Ellipsis,Folder,FolderOpen,KeyRound,MessageSquarePlus,Pencil,Plus,RotateCcw,Settings,Shield,Square,Trash2,X,XCircle} from "lucide-react";
import type {AppInfo,AppearancePreferences,CompletionReport,PermissionState,ProjectInfo,ProviderProfile,SessionInfo,SidecarEvent,TranscriptEntry} from "../shared/protocol";
import {MarkdownText} from "./MarkdownText";
import {buildTimeline,MessageItem,ToolActivity} from "./ToolActivity";
import {SettingsPage} from "./SettingsPage";

type PendingPermission={request_id:string;tool_name:string;risk:string;arguments:Record<string,unknown>};
type Connection="connected"|"recovering"|"disconnected";

export function App(){
 const [projects,setProjects]=useState<ProjectInfo[]>([]),[workspace,setWorkspace]=useState<string|null>(null),[sessions,setSessions]=useState<Record<string,SessionInfo[]>>({}),[expanded,setExpanded]=useState<Set<string>>(new Set()),[visible,setVisible]=useState<Record<string,number>>({});
 const [active,setActive]=useState<SessionInfo|null>(null),[permissions,setPermissions]=useState<PermissionState>({mode:"ask",approved_tools:[]}),[entries,setEntries]=useState<TranscriptEntry[]>([]);
 const [historyCursor,setHistoryCursor]=useState<number|null>(null),[hasOlder,setHasOlder]=useState(false);
 const [draft,setDraft]=useState(""),[stream,setStream]=useState(""),[busy,setBusy]=useState(false),[status,setStatus]=useState("Ready"),[error,setError]=useState<string|null>(null),[pending,setPending]=useState<PendingPermission|null>(null);
 const [connection,setConnection]=useState<Connection>("connected"),[completion,setCompletion]=useState<CompletionReport|null>(null),[renaming,setRenaming]=useState(false),[renameDraft,setRenameDraft]=useState("");
 const [showPermissions,setShowPermissions]=useState(false),[projectMenu,setProjectMenu]=useState<string|null>(null),[projectToRemove,setProjectToRemove]=useState<string|null>(null),[removingProject,setRemovingProject]=useState(false),[draftProject,setDraftProject]=useState<string|null>(null);
 const previousConnection=useRef(connection),eventSequence=useRef(0),viewport=useRef<HTMLDivElement|null>(null),loadingOlder=useRef(false),lastScrollTop=useRef(0);
 const [showSettings,setShowSettings]=useState(false),[profile,setProfile]=useState<ProviderProfile>({provider:"openai-compatible",model:"deepseek-v4-pro",judgeModel:"deepseek-v4-flash",baseUrl:"https://api.deepseek.com",hasApiKey:false}),[apiKey,setApiKey]=useState("");
 const [appearance,setAppearance]=useState<AppearancePreferences>({theme:"system",density:"comfortable"}),[appInfo,setAppInfo]=useState<AppInfo|null>(null);
 const title=active?.title||"New task",hasTask=Boolean(active||draftProject);

 useEffect(()=>{void Promise.all([refreshProjects(),window.noval.getProviderProfile().then(value=>{if(value)setProfile(value)}),window.noval.getAppearance().then(applyAppearance)]).catch(e=>setError(message(e)));return window.noval.onEvent(handleEvent)},[]);
 useEffect(()=>{const recovered=previousConnection.current!=="connected"&&connection==="connected";previousConnection.current=connection;if(!recovered||!active)return;void restoreActive()},[connection,active?.session_id]);
 useEffect(()=>{if(!projectMenu&&!projectToRemove)return;function keydown(event:KeyboardEvent){if(event.key==="Escape"&&!removingProject){setProjectMenu(null);setProjectToRemove(null)}}function pointerdown(event:PointerEvent){const target=event.target;if(projectMenu&&target instanceof Element&&!target.closest(".project-menu")&&!target.closest(".project-actions-trigger"))setProjectMenu(null)}document.addEventListener("keydown",keydown);document.addEventListener("pointerdown",pointerdown);return()=>{document.removeEventListener("keydown",keydown);document.removeEventListener("pointerdown",pointerdown)}},[projectMenu,projectToRemove,removingProject]);

 async function refreshProjects(){const list=await window.noval.listProjects();setProjects(list);const current=list.find(item=>item.active)?.path??null;setWorkspace(current);setExpanded(old=>{const next=new Set(old);if(current)next.add(current);return next});const pages=await Promise.all(list.map(async project=>[project.path,await window.noval.projectSessions(project.path)] as const));setSessions(Object.fromEntries(pages))}
 async function restoreActive(){if(!active)return;try{const result=await window.noval.resumeSession(active.session_id);setActive(result.session);setPermissions(result.permissions);const replay=await window.noval.replayEvents(active.session_id,eventSequence.current);eventSequence.current=replay.next_sequence;if(replay.gap_detected)setStatus("Recovered from transcript");await loadLatest(active.session_id);setBusy(false);setStream("")}catch(e){setError(`Runtime recovered, but the task could not be restored: ${message(e)}`)}}
 function handleEvent(value:SidecarEvent){const e=value.event,p=value.payload as any;if(typeof p.sequence==="number")eventSequence.current=Math.max(eventSequence.current,p.sequence);if(e==="host.connection"){setConnection(p.state);if(p.state!=="connected")setPending(null);setStatus(p.state==="connected"?"Ready":p.state==="recovering"?"Recovering runtime":"Runtime unavailable");return}if(e==="model.started"){setStatus("Generating");setStream("")}if(e==="model.output.delta")setStream(v=>v+String(p.text??p.delta??""));if(e==="tool.started")setStatus(`Running ${p.tool_name??"tool"}`);if(e==="validation.started")setStatus("Validating");if(e==="permission.request"){setPending(p.request as PendingPermission);setStatus("Waiting for approval")}if(e==="turn.completed"||e==="turn.failed"){setPending(null);setStatus(e==="turn.completed"?"Ready":"Turn failed")}}
 async function addProject(){try{const value=await window.noval.chooseWorkspace();if(!value)return;await refreshProjects();setWorkspace(value);setExpanded(old=>new Set(old).add(value));setActive(null);setDraftProject(null);setEntries([])}catch(e){setError(message(e))}}
 async function activateProject(path:string){await window.noval.activateProject(path);setWorkspace(path);setProjects(items=>items.map(item=>({...item,active:item.path===path})))}
 async function toggleProject(project:ProjectInfo){try{await activateProject(project.path);setExpanded(old=>{const next=new Set(old);next.has(project.path)?next.delete(project.path):next.add(project.path);return next});setActive(null);setDraftProject(null);setEntries([])}catch(e){setError(message(e))}}
 async function beginSession(path:string){try{await activateProject(path);setExpanded(old=>new Set(old).add(path));setActive(null);setDraftProject(path);setPermissions({mode:"ask",approved_tools:[]});setPending(null);setEntries([]);setCompletion(null);setDraft("")}catch(e){setError(message(e))}}
 async function openSession(path:string,item:SessionInfo){try{setError(null);setCompletion(null);setPending(null);await activateProject(path);const result=active?.session_id===item.session_id?{session:active,permissions}:await window.noval.resumeSession(item.session_id);setActive(result.session);setDraftProject(null);setPermissions(result.permissions);const replay=await window.noval.replayEvents(item.session_id,0);eventSequence.current=replay.next_sequence;await loadLatest(item.session_id)}catch(e){setError(message(e))}}
 async function removeProject(){const path=projectToRemove;if(!path||removingProject)return;setRemovingProject(true);try{const list=await window.noval.removeProject(path);setProjects(list);setSessions(old=>{const next={...old};delete next[path];return next});if(workspace===path){setWorkspace(list.find(item=>item.active)?.path??null);setActive(null);setDraftProject(null);setEntries([])}setProjectToRemove(null)}catch(e){setError(message(e))}finally{setRemovingProject(false)}}
 async function renameSession(){if(!active||!renameDraft.trim())return;try{const updated=await window.noval.renameSession(active.session_id,renameDraft.trim());setActive(updated);setSessions(old=>Object.fromEntries(Object.entries(old).map(([path,items])=>[path,items.map(item=>item.session_id===updated.session_id?updated:item)])));setRenaming(false)}catch(e){setError(message(e))}}
 async function send(event:FormEvent){event.preventDefault();const projectPath=active?.workdir??draftProject;if(!projectPath||!draft.trim()||busy||connection!=="connected")return;const text=draft.trim();let current=active;setDraft("");setBusy(true);setCompletion(null);try{if(!current){await activateProject(projectPath);const created=await window.noval.createSession();current=created.session;setActive(current);setDraftProject(null);setPermissions(created.permissions)}setEntries(old=>[...old,{sequence:Date.now(),role:"user",text,timestamp:null,tool_calls:[],tool_results:[]}]);scrollToBottom();const result=await window.noval.startTurn(current.session_id,text);setCompletion(result.completion);await loadLatest(current.session_id);setStream("")}catch(e){setError(message(e))}finally{const persisted=await window.noval.projectSessions(projectPath).catch(()=>sessions[projectPath]??[]);setSessions(old=>({...old,[projectPath]:persisted}));if(current){const stored=persisted.find(item=>item.session_id===current!.session_id);if(stored)setActive({...stored,is_open:true});else{setActive(null);setDraftProject(projectPath)}}setBusy(false);setStatus("Ready")}}
 async function loadLatest(sessionId:string){const page=await window.noval.transcriptHistory(sessionId);setEntries(page.entries);setHistoryCursor(page.previous_sequence);setHasOlder(page.has_more);scrollToBottom()}
 async function loadOlder(){if(!active||!hasOlder||historyCursor===null||loadingOlder.current)return;const element=viewport.current;if(!element)return;loadingOlder.current=true;const oldHeight=element.scrollHeight,oldTop=element.scrollTop;try{const page=await window.noval.transcriptHistory(active.session_id,historyCursor);setEntries(current=>{const known=new Set(current.map(item=>item.sequence));return [...page.entries.filter(item=>!known.has(item.sequence)),...current]});setHistoryCursor(page.previous_sequence);setHasOlder(page.has_more);window.requestAnimationFrame(()=>{if(viewport.current){viewport.current.scrollTop=viewport.current.scrollHeight-oldHeight+oldTop;lastScrollTop.current=viewport.current.scrollTop}loadingOlder.current=false})}catch(e){loadingOlder.current=false;setError(message(e))}}
 function scrollToBottom(){window.requestAnimationFrame(()=>{if(viewport.current){viewport.current.scrollTop=viewport.current.scrollHeight;lastScrollTop.current=viewport.current.scrollTop}})}
 function handleConversationScroll(element:HTMLDivElement){const current=element.scrollTop,movingUp=current<lastScrollTop.current;lastScrollTop.current=current;if(movingUp&&current<=32)void loadOlder()}
 async function toggleFullAccess(){if(!active)return;const next=permissions.mode==="ask"?"full_access":"ask";if(next==="full_access"&&!confirm("Full access skips approval prompts for this Session. Workspace confinement, sandboxing, Hooks, redaction, and your requested scope still apply. Continue?"))return;try{setPermissions(await window.noval.setPermissionMode(active.session_id,next))}catch(e){setError(message(e))}}
 async function resolve(decision:"allow_once"|"allow_session"|"deny"){if(!pending)return;try{await window.noval.resolvePermission(pending.request_id,decision);setPending(null);setStatus("Running")}catch(e){setError(message(e))}}
 async function revokeTool(tool:string){if(active)try{setPermissions(await window.noval.revokeTool(active.session_id,tool))}catch(e){setError(message(e))}}
 async function resetPermissions(){if(!active||!confirm("Reset this Session to Ask mode and remove every saved tool grant?"))return;try{setPermissions(await window.noval.resetPermissions(active.session_id))}catch(e){setError(message(e))}}
 async function openSettings(){try{const [value,info,storedAppearance]=await Promise.all([window.noval.getProviderProfile(),window.noval.appInfo(),window.noval.getAppearance()]);if(value)setProfile(value);setAppInfo(info);applyAppearance(storedAppearance);setShowSettings(true)}catch(e){setError(message(e))}}
 async function saveSettings(e:FormEvent){e.preventDefault();try{const saved=await window.noval.saveProviderProfile({...profile,apiKey:apiKey||undefined});setProfile(saved);setApiKey("");setActive(null);setDraftProject(null);setEntries([]);await refreshProjects();return true}catch(err){setError(message(err));return false}}
 async function saveAppearance(value:AppearancePreferences){try{const saved=await window.noval.saveAppearance(value);applyAppearance(saved)}catch(err){setError(message(err))}}
 function applyAppearance(value:AppearancePreferences){setAppearance(value);document.documentElement.dataset.theme=value.theme;document.documentElement.dataset.density=value.density}

 const grouped=useMemo(()=>entries.filter(x=>x.text||x.tool_calls.length||x.tool_results.length),[entries]),timeline=useMemo(()=>buildTimeline(grouped),[grouped]);
 if(showSettings)return <SettingsPage profile={profile} setProfile={setProfile} apiKey={apiKey} setApiKey={setApiKey} appearance={appearance} saveAppearance={saveAppearance} appInfo={appInfo} workspace={workspace} projectCount={projects.length} sessionCount={Object.values(sessions).reduce((total,items)=>total+items.length,0)} saveProvider={saveSettings} close={()=>setShowSettings(false)} error={error} dismissError={()=>setError(null)}/>;
 return <div className="shell">
  <aside className="sidebar project-sidebar">
   <header className="brand"><strong>Noval</strong></header>
   <div className="project-heading"><span>Projects</span><div><button aria-label="Add project" onClick={addProject}><Plus size={17}/></button></div></div>
   <nav className="project-tree" aria-label="Projects">{projects.map(project=>{const items=sessions[project.path]??[],limit=visible[project.path]??5,open=expanded.has(project.path),menuOpen=projectMenu===project.path;return <section className="project-node" key={project.path}><div className={`project-row ${project.active?"current":""}`}><button className="project-main" onClick={()=>toggleProject(project)} title={project.path}>{open?<FolderOpen size={17}/>:<Folder size={17}/>}<span>{project.name}</span></button><div className="hover-actions"><button className="project-actions-trigger" aria-label={`Project actions for ${project.name}`} aria-haspopup="menu" aria-expanded={menuOpen} onClick={()=>setProjectMenu(menuOpen?null:project.path)}><Ellipsis size={15}/></button><button aria-label={`New task in ${project.name}`} onClick={()=>beginSession(project.path)}><MessageSquarePlus size={15}/></button></div>{menuOpen&&<div className="menu project-menu" role="menu" aria-label={`Actions for ${project.name}`}><button role="menuitem" onClick={()=>{void window.noval.revealProject(project.path);setProjectMenu(null)}}><FolderOpen size={16}/>Open in File Explorer</button><button role="menuitem" className="danger" onClick={()=>{setProjectMenu(null);setProjectToRemove(project.path)}}><Trash2 size={16}/>Remove project</button></div>}</div>{open&&<div className="session-list">{items.slice(0,limit).map(item=><button key={item.session_id} className={`session-row ${active?.session_id===item.session_id?"active":""}`} onClick={()=>openSession(project.path,item)}><span>{item.title||"Untitled task"}</span></button>)}{items.length>limit&&<button className="show-more" onClick={()=>setVisible(old=>({...old,[project.path]:limit+5}))}>Show {Math.min(5,items.length-limit)} more</button>}{items.length===0&&<p className="no-sessions">No tasks yet</p>}</div>}</section>})}{projects.length===0&&<p className="no-projects">Add a project to begin. Your folders stay local.</p>}</nav>
   <footer><button className="settings-link" onClick={openSettings}><Settings size={16}/>Settings</button><span className="connection"><span className={`status-dot ${connection}`}/>{connection==="connected"?"Runtime connected":connection==="recovering"?"Recovering runtime":"Runtime unavailable"}</span></footer>
  </aside>
  <main className="workspace-pane">
   <header className="topbar">{active?<div>{renaming?<form className="rename" onSubmit={e=>{e.preventDefault();void renameSession()}}><input aria-label="Task title" autoFocus value={renameDraft} onChange={e=>setRenameDraft(e.target.value)}/><button aria-label="Save title"><CheckCircle2 size={15}/></button><button type="button" aria-label="Cancel rename" onClick={()=>setRenaming(false)}><XCircle size={15}/></button></form>:<h1>{title}<button className="rename-trigger" aria-label="Rename task" onClick={()=>{setRenameDraft(title);setRenaming(true)}}><Pencil size={12}/></button></h1>}<p>{workspace}</p></div>:draftProject?<div><h1>New task</h1><p>{draftProject}</p></div>:<div><h1>{workspace?leaf(workspace):"Noval"}</h1><p>{workspace||"Add a project from the sidebar"}</p></div>}{active&&<div className="top-actions"><button className="access" onClick={()=>setShowPermissions(v=>!v)}><KeyRound size={14}/>{permissions.approved_tools.length} grants</button><button className={`access ${permissions.mode}`} onClick={toggleFullAccess}><Shield size={15}/>{permissions.mode==="full_access"?"Full access":"Ask permission"}</button></div>}</header>
   {showPermissions&&active&&<section className="grants-panel"><header><div><strong>Session permissions</strong><small>Saved exactly as Noval Runtime reports them.</small></div><button onClick={resetPermissions}><RotateCcw size={13}/>Reset all</button></header>{permissions.approved_tools.length?<ul>{permissions.approved_tools.map(tool=><li key={tool}><code>{tool}</code><button onClick={()=>revokeTool(tool)}>Revoke</button></li>)}</ul>:<p>No tools are approved for this Session.</p>}</section>}
   {!hasTask?<EmptyState projectName={workspace?leaf(workspace):null}/>:<><div className="conversation-viewport" ref={viewport} onScroll={event=>handleConversationScroll(event.currentTarget)} onWheel={event=>{if(event.deltaY<0&&event.currentTarget.scrollTop<=32)void loadOlder()}}>{timeline.length===0&&!stream&&!completion?<EmptyState projectName={leaf(active?.workdir??draftProject!)}/>:<div className="conversation">{hasOlder&&<div className="history-loader" aria-label="Older messages available">Scroll up to load earlier messages</div>}{timeline.map(item=>item.type==="message"?<ConversationMessage key={item.key} item={item}/>:<ToolActivity key={item.key} activity={item}/>)}{stream&&<article className="message message-assistant"><MarkdownText text={stream} streaming/></article>}{completion&&<CompletionCard report={completion}/>}</div>}</div><form className="composer" onSubmit={send}><textarea aria-label="Message Noval" value={draft} onChange={e=>setDraft(e.target.value)} placeholder="Ask Noval to inspect, build, or verify" disabled={connection!=="connected"} onKeyDown={e=>{if(e.key==="Enter"&&!e.shiftKey){e.preventDefault();e.currentTarget.form?.requestSubmit()}}}/><div className="composer-row"><div><button type="button" aria-label="Mention context"><AtSign size={16}/></button><span><span className={`status-dot ${connection}`}/>{status}</span></div>{busy?<button type="button" className="send stop" onClick={()=>active&&window.noval.cancelTurn(active.session_id)}><Square size={13}/></button>:<button className="send" disabled={!draft.trim()||connection!=="connected"} aria-label="Send"><ArrowUp size={17}/></button>}</div></form></>}
    {error&&<div className="error" role="alert"><strong>Something needs attention</strong><span>{error}</span><button onClick={()=>setError(null)}>Dismiss</button></div>}
    {pending&&<div className="scrim"><section className="permission"><div className="permission-icon"><KeyRound size={20}/></div><p className="eyebrow">PERMISSION REQUIRED</p><h2>Allow {pending.tool_name}?</h2><p>This <strong>{pending.risk}</strong> action needs your approval.</p><pre>{safePreview(pending.arguments)}</pre><div className="actions"><button onClick={()=>resolve("deny")}>Deny</button><button onClick={()=>resolve("allow_session")}>Allow for Session</button><button className="primary" onClick={()=>resolve("allow_once")}>Allow once</button></div></section></div>}
    {projectToRemove&&<div className="scrim project-remove-scrim" onPointerDown={event=>{if(event.target===event.currentTarget&&!removingProject)setProjectToRemove(null)}}><section className="confirm-dialog" role="dialog" aria-modal="true" aria-labelledby="remove-project-title"><button className="dialog-close" aria-label="Close remove project dialog" disabled={removingProject} onClick={()=>setProjectToRemove(null)}><X size={18}/></button><h2 id="remove-project-title">Remove {leaf(projectToRemove)}?</h2><p>This removes the project from the sidebar. Files and Sessions on disk will not be deleted.</p><div className="dialog-actions"><button autoFocus disabled={removingProject} onClick={()=>setProjectToRemove(null)}>Cancel</button><button className="danger-action" disabled={removingProject} onClick={removeProject}>{removingProject?"Removing…":"Remove"}</button></div></section></div>}
   </main>
 </div>
}

function EmptyState({projectName}:{projectName:string|null}){return <section className="empty-state">{projectName?<h2>我们应该在 <span>{projectName}</span> 中构建什么？</h2>:<h2>添加一个项目以开始使用 Noval</h2>}</section>}
function ConversationMessage({item}:{item:MessageItem}){
 const [copied,setCopied]=useState(false),displayTime=formatTimestamp(item.timestamp);
 async function copy(){await window.noval.copyText(item.text);setCopied(true);window.setTimeout(()=>setCopied(false),1400)}
 return <article className={`message message-${item.role}`}><MarkdownText text={item.text}/>{item.showMeta&&<footer className="message-meta">{displayTime&&<time dateTime={item.timestamp!} title={formatFullTimestamp(item.timestamp!)}>{displayTime}</time>}<button type="button" aria-label={copied?"Copied":"Copy message"} onClick={copy}>{copied?<Check size={14}/>:<Copy size={14}/>}</button></footer>}</article>
}
function CompletionCard({report}:{report:CompletionReport}){return <section className={`completion ${report.status}`} aria-label="Completion evidence"><div><strong>{report.status==="completed"?"Verified complete":report.status==="incomplete"?"Incomplete":"Completion uncertain"}</strong><small>Evidence evaluated by Noval Runtime</small></div>{report.criteria.length>0&&<ul>{report.criteria.map(item=><li key={item.criterion_id}><span>{item.criterion_id}</span><strong>{item.status}</strong><small>{item.source||"No verification source"}</small></li>)}</ul>}</section>}
function leaf(value:string){return value.split(/[\\/]/).filter(Boolean).at(-1)||value}function message(e:unknown){return e instanceof Error?e.message:"An unexpected error occurred."}function safePreview(v:unknown){try{return JSON.stringify(v,null,2).slice(0,1600)}catch{return "Details unavailable"}}
function formatTimestamp(value:string|null){if(!value)return "";const date=new Date(value);return Number.isNaN(date.valueOf())?"":new Intl.DateTimeFormat(undefined,{hour:"2-digit",minute:"2-digit"}).format(date)}
function formatFullTimestamp(value:string){const date=new Date(value);return Number.isNaN(date.valueOf())?value:new Intl.DateTimeFormat(undefined,{dateStyle:"medium",timeStyle:"short"}).format(date)}
