import {FormEvent,useEffect,useMemo,useRef,useState} from "react";
import {Bot,CheckCircle2,ChevronDown,Download,FolderOpen,KeyRound,MessageSquarePlus,Pencil,RotateCcw,Settings,Shield,Square,TerminalSquare,XCircle} from "lucide-react";
import type {CompletionReport,PermissionState,ProviderProfile,SessionInfo,SidecarEvent,TranscriptEntry} from "../shared/protocol";

type PendingPermission={request_id:string;tool_name:string;risk:string;arguments:Record<string,unknown>};

export function App(){
 const [workspace,setWorkspace]=useState<string|null>(null),[sessions,setSessions]=useState<SessionInfo[]>([]),[active,setActive]=useState<SessionInfo|null>(null);
 const [permissions,setPermissions]=useState<PermissionState>({mode:"ask",approved_tools:[]}),[entries,setEntries]=useState<TranscriptEntry[]>([]);
 const [draft,setDraft]=useState(""),[stream,setStream]=useState(""),[busy,setBusy]=useState(false),[status,setStatus]=useState("Ready"),[error,setError]=useState<string|null>(null),[pending,setPending]=useState<PendingPermission|null>(null);
 const [connection,setConnection]=useState<"connected"|"recovering"|"disconnected">("connected"),[completion,setCompletion]=useState<CompletionReport|null>(null),[renaming,setRenaming]=useState(false),[renameDraft,setRenameDraft]=useState("");
 const [showPermissions,setShowPermissions]=useState(false);
 const previousConnection=useRef(connection),eventSequence=useRef(0);
 const [showSettings,setShowSettings]=useState(false),[profile,setProfile]=useState<ProviderProfile>({provider:"openai-compatible",model:"deepseek-v4-pro",judgeModel:"deepseek-v4-flash",baseUrl:"https://api.deepseek.com",hasApiKey:false}),[apiKey,setApiKey]=useState("");
 const title=active?.title||"New task";
 useEffect(()=>{void window.noval.getWorkspace().then(async value=>{setWorkspace(value);if(value)setSessions(await window.noval.listSessions())}).catch(e=>setError(message(e)));return window.noval.onEvent(handleEvent)},[]);
 useEffect(()=>{const recovered=previousConnection.current!=="connected"&&connection==="connected";previousConnection.current=connection;if(!recovered||!active)return;void (async()=>{try{const result=await window.noval.resumeSession(active.session_id);setActive(result.session);setPermissions(result.permissions);const replay=await window.noval.replayEvents(active.session_id,eventSequence.current);if(replay.gap_detected)setStatus("Recovered from transcript");eventSequence.current=replay.next_sequence;const page=await window.noval.transcript(active.session_id);setEntries(page.entries);setBusy(false);setStream("")}catch(e){setError(`Runtime recovered, but the task could not be restored: ${message(e)}`)}})()},[connection,active?.session_id]);
 function handleEvent(message:SidecarEvent){const e=message.event,p=message.payload as any;if(typeof p.sequence==="number")eventSequence.current=Math.max(eventSequence.current,p.sequence);if(e==="host.connection"){setConnection(p.state);setStatus(p.state==="connected"?"Ready":p.state==="recovering"?"Recovering runtime":"Runtime unavailable");return}if(e==="model.started"){setStatus("Generating");setStream("")}if(e==="model.output.delta")setStream(v=>v+String(p.text??p.delta??""));if(e==="tool.started")setStatus(`Running ${p.tool_name??"tool"}`);if(e==="validation.started")setStatus("Validating");if(e==="permission.request"){setPending(p.request as PendingPermission);setStatus("Waiting for approval")}if(e==="turn.completed"||e==="turn.failed"){setStatus(e==="turn.completed"?"Ready":"Turn failed")}}
 async function choose(){try{const value=await window.noval.chooseWorkspace();if(!value)return;setWorkspace(value);setActive(null);setEntries([]);setSessions(await window.noval.listSessions())}catch(e){setError(message(e))}}
 async function openSession(item:SessionInfo){try{setError(null);setCompletion(null);const result=active?.session_id===item.session_id?{session:active,permissions}:await window.noval.resumeSession(item.session_id);setActive(result.session);setPermissions(result.permissions);const replay=await window.noval.replayEvents(item.session_id,0);eventSequence.current=replay.next_sequence;if(replay.gap_detected)setStatus("Recovered from transcript");const page=await window.noval.transcript(item.session_id);setEntries(page.entries)}catch(e){setError(message(e))}}
 async function createSession(){try{const result=await window.noval.createSession();setSessions(v=>[result.session,...v]);setActive(result.session);setPermissions(result.permissions);setEntries([])}catch(e){setError(message(e))}}
 async function send(event:FormEvent){event.preventDefault();if(!active||!draft.trim()||busy||connection!=="connected")return;const text=draft.trim();setDraft("");setBusy(true);setCompletion(null);setEntries(v=>[...v,{sequence:Date.now(),role:"user",text,timestamp:null,tool_calls:[],tool_results:[]}]);try{const result=await window.noval.startTurn(active.session_id,text);setCompletion(result.completion);const page=await window.noval.transcript(active.session_id);setEntries(page.entries);setStream("")}catch(e){setError(message(e))}finally{setBusy(false);setStatus("Ready")}}
 async function toggleFullAccess(){if(!active)return;const next=permissions.mode==="ask"?"full_access":"ask";if(next==="full_access"&&!confirm("Full access skips approval prompts for this Session. Workspace confinement, sandboxing, Hooks, redaction, and your requested scope still apply. Continue?"))return;try{setPermissions(await window.noval.setPermissionMode(active.session_id,next))}catch(e){setError(message(e))}}
 async function resolve(decision:"allow_once"|"allow_session"|"deny"){if(!pending)return;try{await window.noval.resolvePermission(pending.request_id,decision);setPending(null);setStatus("Running")}catch(e){setError(message(e))}}
 async function renameSession(){if(!active||!renameDraft.trim())return;try{const updated=await window.noval.renameSession(active.session_id,renameDraft.trim());setActive(updated);setSessions(v=>v.map(item=>item.session_id===updated.session_id?updated:item));setRenaming(false)}catch(e){setError(message(e))}}
 async function revokeTool(tool:string){if(!active)return;try{setPermissions(await window.noval.revokeTool(active.session_id,tool))}catch(e){setError(message(e))}}
 async function resetPermissions(){if(!active||!confirm("Reset this Session to Ask mode and remove every saved tool grant?"))return;try{setPermissions(await window.noval.resetPermissions(active.session_id))}catch(e){setError(message(e))}}
 async function exportDiagnostics(){try{const path=await window.noval.exportDiagnostics();if(path)setStatus("Diagnostics exported")}catch(e){setError(message(e))}}
 async function openSettings(){try{const value=await window.noval.getProviderProfile();if(value)setProfile(value);setShowSettings(true)}catch(e){setError(message(e))}}
 async function saveSettings(e:FormEvent){e.preventDefault();try{const saved=await window.noval.saveProviderProfile({...profile,apiKey:apiKey||undefined});setProfile(saved);setApiKey("");setShowSettings(false);setActive(null);setSessions(workspace?await window.noval.listSessions():[]);setEntries([])}catch(err){setError(message(err))}}
 const grouped=useMemo(()=>entries.filter(x=>x.text||x.tool_calls.length||x.tool_results.length),[entries]);
 if(!workspace)return <main className="welcome"><button className="welcome-settings" onClick={openSettings} aria-label="Provider settings"><Settings size={18}/></button><div className="brand-mark"><Bot size={28}/></div><p className="eyebrow">NOVAL DESKTOP</p><h1>Give capable agents<br/>a trustworthy place to act.</h1><p className="lede">Choose a folder. Noval keeps execution, permission, continuity, and evidence inside that workspace boundary.</p><button className="primary large" onClick={choose}><FolderOpen size={18}/>Choose workspace</button><p className="privacy">Local-first preview · No remote telemetry</p>{showSettings&&settingsDialog(profile,setProfile,apiKey,setApiKey,saveSettings,()=>setShowSettings(false))}</main>;
 return <div className="shell">
  <aside className="sidebar"><header><div className="logo"><Bot size={18}/><span>Noval</span></div></header><button className="workspace" onClick={choose}><FolderOpen size={16}/><span><small>WORKSPACE</small>{leaf(workspace)}</span><ChevronDown size={14}/></button><button className="new-task" onClick={createSession}><MessageSquarePlus size={16}/>New task</button><nav>{sessions.map(s=><button key={s.session_id} className={active?.session_id===s.session_id?"task active":"task"} onClick={()=>openSession(s)}><span>{s.title||"Untitled task"}</span><small>{s.model}</small></button>)}</nav><footer><button className="settings-link" onClick={openSettings}><Settings size={14}/>Provider settings</button><button className="settings-link" onClick={exportDiagnostics}><Download size={14}/>Export diagnostics</button><span><span className={`status-dot ${connection}`}/>{connection==="connected"?"Sidecar connected":connection==="recovering"?"Recovering sidecar":"Sidecar unavailable"}</span></footer></aside>
  <section className="content"><header className="topbar"><div>{renaming?<form className="rename" onSubmit={e=>{e.preventDefault();void renameSession()}}><input aria-label="Task title" autoFocus value={renameDraft} onChange={e=>setRenameDraft(e.target.value)}/><button aria-label="Save title"><CheckCircle2 size={15}/></button><button type="button" aria-label="Cancel rename" onClick={()=>setRenaming(false)}><XCircle size={15}/></button></form>:<h2>{title}<button className="rename-trigger" aria-label="Rename task" onClick={()=>{setRenameDraft(title);setRenaming(true)}}><Pencil size={12}/></button></h2>}<p>{workspace}</p></div><div className="top-actions"><button className="access grants" onClick={()=>setShowPermissions(v=>!v)}><KeyRound size={14}/>{permissions.approved_tools.length} grants</button><button className={`access ${permissions.mode}`} onClick={toggleFullAccess}><Shield size={15}/>{permissions.mode==="full_access"?"Full access":"Ask permission"}</button></div></header>
  {showPermissions&&active&&<section className="grants-panel"><header><div><strong>Session permissions</strong><small>Saved exactly as Noval Runtime reports them.</small></div><button onClick={resetPermissions}><RotateCcw size={13}/>Reset all</button></header>{permissions.approved_tools.length?<ul>{permissions.approved_tools.map(tool=><li key={tool}><code>{tool}</code><button onClick={()=>revokeTool(tool)}>Revoke</button></li>)}</ul>:<p>No tools are approved for this Session.</p>}</section>}
  {!active?<div className="empty"><div className="orb"><TerminalSquare size={26}/></div><h2>Start with a task</h2><p>Noval will choose the method. The runtime keeps every action bounded, recoverable, and verifiable.</p><button className="primary" onClick={createSession}><MessageSquarePlus size={17}/>Create task</button></div>:<><div className="conversation">{grouped.map((entry,i)=><article key={`${entry.sequence}-${i}`} className={`message ${entry.role}`}><div className="role">{entry.role==="user"?"You":"Noval"}</div>{entry.text&&<div className="body">{entry.text}</div>}{entry.tool_calls.map(t=><div className="tool" key={t.call_id}><TerminalSquare size={15}/><span>Called <strong>{t.name}</strong></span><small>{t.argument_keys.join(", ")}</small></div>)}{entry.tool_results.map(t=><div className={`tool result ${t.is_error?"failed":""}`} key={t.call_id}>{t.is_error?"Tool failed":"Tool completed"}</div>)}</article>)}{stream&&<article className="message assistant"><div className="role">Noval</div><div className="body">{stream}<span className="cursor"/></div></article>}{completion&&<CompletionCard report={completion}/>}</div><form className="composer" onSubmit={send}><textarea aria-label="Message Noval" value={draft} onChange={e=>setDraft(e.target.value)} placeholder="Ask Noval to inspect, build, or verify…" disabled={connection!=="connected"} onKeyDown={e=>{if(e.key==="Enter"&&!e.shiftKey){e.preventDefault();e.currentTarget.form?.requestSubmit()}}}/><div className="composer-row"><span><span className={`status-dot ${connection}`}/>{status}</span>{busy?<button type="button" className="send stop" onClick={()=>active&&window.noval.cancelTurn(active.session_id)}><Square size={14}/></button>:<button className="send" disabled={!draft.trim()||connection!=="connected"} aria-label="Send">↑</button>}</div></form></>}
  {error&&<div className="error" role="alert"><strong>Something needs attention</strong><span>{error}</span><button onClick={()=>setError(null)}>Dismiss</button></div>}
  {pending&&<div className="scrim"><section className="permission"><div className="permission-icon"><KeyRound size={20}/></div><p className="eyebrow">PERMISSION REQUIRED</p><h2>Allow {pending.tool_name}?</h2><p>This <strong>{pending.risk}</strong> action needs your approval.</p><pre>{safePreview(pending.arguments)}</pre><div className="actions"><button onClick={()=>resolve("deny")}>Deny</button><button onClick={()=>resolve("allow_session")}>Allow for Session</button><button className="primary" onClick={()=>resolve("allow_once")}>Allow once</button></div></section></div>}
  {showSettings&&settingsDialog(profile,setProfile,apiKey,setApiKey,saveSettings,()=>setShowSettings(false))}
  </section></div>
}
function CompletionCard({report}:{report:CompletionReport}){return <section className={`completion ${report.status}`} aria-label="Completion evidence"><div><strong>{report.status==="completed"?"Verified complete":report.status==="incomplete"?"Incomplete":"Completion uncertain"}</strong><small>Evidence evaluated by Noval Runtime</small></div>{report.criteria.length>0&&<ul>{report.criteria.map(item=><li key={item.criterion_id}><span>{item.criterion_id}</span><strong>{item.status}</strong><small>{item.source||"No verification source"}</small></li>)}</ul>}</section>}
function leaf(path:string){return path.split(/[\\/]/).filter(Boolean).at(-1)||path}function message(e:unknown){return e instanceof Error?e.message:"An unexpected error occurred."}function safePreview(v:unknown){try{return JSON.stringify(v,null,2).slice(0,1600)}catch{return "Details unavailable"}}
function settingsDialog(profile:ProviderProfile,setProfile:(v:ProviderProfile)=>void,apiKey:string,setApiKey:(v:string)=>void,save:(e:FormEvent)=>void,close:()=>void){return <div className="scrim"><form className="permission settings-panel" onSubmit={save}><div className="permission-icon"><Settings size={20}/></div><p className="eyebrow">PROVIDER SETTINGS</p><h2>Connect a model</h2><label>Provider<select value={profile.provider} onChange={e=>setProfile({...profile,provider:e.target.value as ProviderProfile['provider']})}><option value="openai-compatible">OpenAI-compatible</option><option value="anthropic">Anthropic</option></select></label><label>Model<input value={profile.model} onChange={e=>setProfile({...profile,model:e.target.value})}/></label><label>Judge model<input value={profile.judgeModel} onChange={e=>setProfile({...profile,judgeModel:e.target.value})}/></label><label>Base URL<input value={profile.baseUrl} onChange={e=>setProfile({...profile,baseUrl:e.target.value})}/></label><label>API key<input type="password" value={apiKey} placeholder={profile.hasApiKey?"Saved securely · leave blank to keep":"Enter API key"} onChange={e=>setApiKey(e.target.value)} autoComplete="off"/></label><p className="settings-note">Saved keys are encrypted with operating-system credential protection and never returned to the Renderer.</p><div className="actions"><button type="button" onClick={close}>Cancel</button><button className="primary">Save and restart runtime</button></div></form></div>}
