"""Noval — a small, general-purpose agent core."""
# Import builtins for the side effect of registering built-in @tool functions.
from . import builtins as _builtins  # noqa: F401

from .api import (  # noqa: F401
    API_SCHEMA_VERSION,
    AcceptanceCriterion,
    ActionReceipt,
    ApiFormatError,
    CompletionReport,
    CompletionStatus,
    CriterionReport,
    CriterionStatus,
    ErrorInfo,
    EvidenceOutcome,
    EventPage,
    EventType,
    GoalContract,
    NovalError,
    PermissionDecision,
    PermissionRequest,
    PermissionStateView,
    PersistedProjectInfo,
    RequestInspection,
    RuntimeEvent,
    RuntimeConfiguration,
    RuntimeOptions,
    SESSION_TITLE_MAX_LENGTH,
    ReceiptKind,
    ReceiptOutcome,
    SemanticAssessment,
    SessionInfo,
    SessionOptions,
    SessionPersistence,
    StopReason,
    TurnMetrics,
    TurnRequest,
    TurnResult,
    TurnStatus,
    TranscriptEntry,
    TranscriptPage,
    TranscriptToolCall,
    TranscriptToolResult,
    VerificationResult,
)
from .application import (  # noqa: F401
    AgentSession,
    ClientFactory,
    ClientSpec,
    EventSink,
    NovalRuntime,
    PermissionHandler,
)
from .client import LLMStreamEvent, StreamingLLMClient  # noqa: F401
from .permissions import PermissionMode  # noqa: F401
